### ISSUE TITLE
Metric reporting wrong value when fail-over occurs

### ISSUE THREAD

**Issue by tanisdlj** [opstree/druid-exporter#100]
One of our druid-overlord failed over to another instance and since that happened, the exporter reported a constant value (false value) until I restarted the process.
![image](https://user-images.githubusercontent.com/1453135/111143765-7df12680-8586-11eb-9683-e1d080a24952.png)

Seems to me than the exporter keeps reporting last known value. If that's the case, maybe you can set a TTL, after which it should then report `null`.

Thanks!

**Comment by iamabhishek-dubey** [comment]
We already have a cleaner package available to clean up these kinds of metrics.
https://github.com/opstree/druid-exporter/blob/master/listener/cleaner.go

Can you please share the example query?

**Comment by tanisdlj** [comment]
Hi @iamabhishek-dubey , it's been a month so I can't remember what it was, but I would say one of the following:
- `druid_emitted_metrics{metric_name="segment-unavailable-count"}`
- `druid_emitted_metrics{metric_name="ingest-handoff-count"}`
- `druid_emitted_metrics{metric_name="segment-underReplicated-count"}`
- `druid_emitted_metrics{metric_name="ingest-kafka-lag"}`

**Comment by iamabhishek-dubey** [comment]
I will take a look at this

**Comment by iamabhishek-dubey** [comment]
This will be fixed in this
https://github.com/opstree/druid-exporter/pull/104
