### ISSUE TITLE
how to config druid to push metrics to druid-exporter

### ISSUE THREAD

**Issue by taoyantu** [opstree/druid-exporter#105]
Hello master:
    I now use ./druid-exporter --druid.url=http://routerip:8888, after startup, you can view many monitoring items through http://local:8080/metrics.
   Are these monitoring items all the data that this druid-exporter project can see? Is there any other configuration method that can receive more monitoring items? How to configure in druid? Modify that file (for example: confi/druid/cluster/_common/common.runtime.properties)? How to configure？Can you tell me?
  thank you very much ！

**Comment by iamabhishek-dubey** [comment]
Just add these configurations in the runtime.properties

```properties
druid.emitter.http.recipientBaseUrl=http://<druid_exporter_url>:<druid_exporter_port>/druid
druid.emitter=http
```
