### ISSUE TITLE
Helm Chart Support for existing secrets

### ISSUE THREAD

**Issue by CrowdSalat** [opstree/druid-exporter#106]
Is it sensible to add an option to the helm chart to load the Druid credentials from an already existing secret? 

We use sealedSecret in our projects so we cannot provide the password direclty as an environment variable to the container. Instead it would be helpful if we could add a reference to a secret. 

Also do you guys now when the druid-exporter in the [prometheus-community ](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-druid-exporter) gets updated?

**Comment by iamabhishek-dubey** [comment]
Yeah it makes sense, also I am the maintainer of prometheus-community's druid exporter. I guess I have missed updating it for a while. I will update it on the weekend.

**Comment by CrowdSalat** [comment]
Glad to hear. I will look into this and create a pull request
