### ISSUE TITLE
Dashboard does not support multiple druid hosts

### ISSUE THREAD

**Issue by xkmato** [opstree/druid-exporter#108]
The dashboard currently does not support multiple druid hosts.

**Comment by mustafacse** [comment]
Any update on this? Most of the time we are going to have distributed setup, muiltiple hosts for data server, how can we capture all in the dashboard?

**Comment by iamabhishek-dubey** [comment]
This is a smaller change at the dashboard level, which can be easily done. We will try to implement this ASAP.
