### ISSUE TITLE
Add possibility to deactivate Helm tests

### ISSUE THREAD

**Issue by mstein11** [opstree/druid-exporter#110]
I would like to have the possibility to deactivate the helm tests. I would propose to add a helm value `testEnabled`. If you agree I can implement and add a pull request for it.

**Comment by mstein11** [comment]
I opened a PR for this feature. Also, would it be possible to bring the latest version of this helm chart to https://github.com/prometheus-community/helm-charts? 

Right now, the latest version there is 0.9.0 with app version v0.8.0, which still suffers from the "interface to a nil conversion error" bug.

**Comment by CrowdSalat** [comment]
If so it would be nice if you could include the PR 107 in your next community update.

**Comment by iamabhishek-dubey** [comment]
Sure @CrowdSalat
