### ISSUE TITLE
Grafana Dashobard is not working

### ISSUE THREAD

**Issue by mustafacse** [opstree/druid-exporter#113]
After installation using tar file. I did run ./druid-exporter and tried opening port with <host>:8080/druid and its just a blank page, I could not see grafana dashboard, <host>:8080/metrics are working. Can someone help what is the issue here?

**Comment by iamabhishek-dubey** [comment]
This is not the bug of exporter or dashboard, are you able to see and query data inside prometheus?

**Comment by mustafacse** [comment]
If we have multiple EC2s do we need to run druid exporter on each machine and add it in prometheus config?

**Comment by iamabhishek-dubey** [comment]
Ofcourse, you have to do that because that's the nature of the exporter. One exporter for one service.

**Comment by iamabhishek-dubey** [comment]
This is not actually a bug so I am closing this
