### ISSUE TITLE
New release any time soon?

### ISSUE THREAD

**Issue by klarose** [opstree/druid-exporter#118]
Hello,

Thanks for the great product! We're running into https://github.com/opstree/druid-exporter/issues/100 in our system. That bug looks to have been fixed the day after the last release was made (v0.10.0). Any chance of a new one any time soon?

Thanks

**Comment by iamabhishek-dubey** [comment]
Hi @klarose ,
We have a plan to release the next version by this week

**Comment by tanisdlj** [comment]
Hi! Any news regarding this? Thanks!
