### ISSUE TITLE
Helm chart 0.11.0 on the helm repo seems to be outdated

### ISSUE THREAD

**Issue by layoaster** [opstree/druid-exporter#124]
Despite having the same release version (0.11.0) the helm chart on the prometheus-community [repository](https://artifacthub.io/packages/helm/prometheus-community/prometheus-druid-exporter) doesn't seem to include the actual release [0.11.0](https://github.com/opstree/druid-exporter/releases/tag/v0.11) of this repo.

I miss things like the `security` config section.

**Comment by applike-ss** [comment]
just realized the same, it does still deliver version 0.8 to me. You can however overwrite this with the help values `image.tag: v0.11`. Note the missing `.0` compared to the chart version. Wished it was consistent with that :-/

**Comment by iamabhishek-dubey** [comment]
Will raise the PR for same :D
