### ISSUE TITLE
Memory leak and exporter becomes unresponsive over time

### ISSUE THREAD

**Issue by netixx** [opstree/druid-exporter#128]
Hello,

I have druid-exporter setup to monitor by druid cluster (around 90 druid nodes running).

I am running into stability issues with druid-exporter. At first it runs as expected, but after a few hours (5 to 6), it is no longer responsive (and metric scraping fails).

Here we can see that the memory slowly increases over time:
![image](https://user-images.githubusercontent.com/1488603/162691320-bb99df01-0029-4c69-a9ff-6fb4d80894fc.png)

As you can see, the prometheus /metrics endpoint response time increases over time (limited to 60s in my setup):
![image](https://user-images.githubusercontent.com/1488603/162691928-baae8563-a3ac-48c5-8404-12ac2f9de661.png)

Looking at metrics usage in prometheus, it seems that druid metrics occupy most of the top 10:
![image](https://user-images.githubusercontent.com/1488603/162695449-ecb8db46-f72a-4e0a-b020-90e9838ca8aa.png)

One cause may be that the exporter is logging `task_id`, but since it is a unique value, the cardinality of those metrics will escape to infinity (which is bad for prometheus scalability).

**Comment by netixx** [comment]
I used the --no-histogram config and it seems much better in terms of memory for the exporter.

I had to drop the druid_emited_metrics at scrape time to avoid creating too many series in prometheus though (it was generating around 15000 series per scrape in my setup).

Now I am down to 5k series per scrape from the druid-exporter (which is still huge, but more manageable).

**Comment by iamabhishek-dubey** [comment]
Please reopen if you face same issue again.
