### ISSUE TITLE
Druid exporter is emitting huge metrics

### ISSUE THREAD

**Issue by sridhara-hpe** [opstree/druid-exporter#133]
Druid is emitting very huge number of metrics which our prometheus cannot handle it
Is there a way to restrict the emitting metrics to some extent or can we decrease the metrics emitting time intervel
Please help us on this issue

**Comment by iamabhishek-dubey** [comment]
I guess this can help you

https://druid.apache.org/docs/latest/configuration/index.html#enabling-metrics.
You can define the frequency of intervals.


*Thanks & Regards*
*Abhishek Dubey*
*Contact No:-* *9560375769*
*Email ID:-* ***@***.**** ***@***.***>

**Comment by iamabhishek-dubey** [comment]
https://druid.apache.org/docs/latest/configuration/index.html#enabling-metrics

This can help you
