### ISSUE TITLE
druid_health_status returns 0 value but druid services return true for health status

### ISSUE THREAD

**Issue by TheIdhem** [opstree/druid-exporter#28]
druid services health check endpoints return true for all individual services but druid exporter for metric druid_health_status returns 0 value.what parameters affect this overall health check metric?

**Comment by iamabhishek-dubey** [comment]
Thanks for the bug report, I will surely check this

**Comment by iamabhishek-dubey** [comment]
So this checks all the druid's component should be running fine

**Comment by iamabhishek-dubey** [comment]
Can you post your response and logs?

**Comment by TheIdhem** [comment]
> So this checks all the druid's component should be running fine

the name of the component that we have are the followings:
coordinator-overload
broker
historical
middleManger
2 peon
router
all this services are already running

**Comment by TheIdhem** [comment]
> Can you post your response and logs?

<img width="628" alt="Screen Shot 2020-06-24 at 6 08 49 pm" src="https://user-images.githubusercontent.com/31737620/85567027-c443d580-b645-11ea-80e7-392fe07652f3.png">

this is the metrics that we get from scraping the exporter in our monitoring system

**Comment by iamabhishek-dubey** [comment]
This screenshot is only providing me the metrics name only, can you show the metric query response, also can you post the stdout logs of druid exporter

**Comment by Chester-Ong** [comment]
Did you configure the **--druid.uri=<value>**. If this is missing it defaults to doing a healthcheck on **http://druid.opstreelabs.in**.

For example if you are running both the druid server and druid-exporter locally, run the command
```
./druid-exporter --druid.uri=http://localhost:8888
```

**Comment by TheIdhem** [comment]
> Did you configure the **--druid.uri=<value>**. If this is missing it defaults to doing a healthcheck on **http://druid.opstreelabs.in**.
> 
> For example if you are running both the druid server and druid-exporter locally, run the command
> 
> ```
> ./druid-exporter --druid.uri=http://localhost:8888
> ```

Ooo yes
i'd been badly configured the exporter and when we pass this parameter my problem has been solved :)))
tnQ for your attention

**Comment by danghuagood** [comment]
> Did you configure the **--druid.uri=<value>**. If this is missing it defaults to doing a healthcheck on **http://druid.opstreelabs.in**.
> 
> For example if you are running both the druid server and druid-exporter locally, run the command
> 
> ```
> ./druid-exporter --druid.uri=http://localhost:8888
> ```
I have the same problem after use implementing commit: db1c4bd646675749fe6858e1cf82b26932b5d24b, here is the messages

![image](https://user-images.githubusercontent.com/8109501/90114787-cee93400-dd85-11ea-8797-6d785f5495e2.png)

the command:
/usr/local/bin/druid-exporter --druid.uri=http://10.18.64.247 --port=10086 --log.level=debug
