### ISSUE TITLE
Error decoding JSON sent by druid: json: cannot unmarshal array into Go struct field DruidEmittedData.dataSource of type string

### ISSUE THREAD

**Issue by busecolak** [opstree/druid-exporter#30]
Hello, 

I'm running the exporter using image `quay.io/opstree/druid-exporter:v0.6` and Druid 0.18.0.

I am getting the below error when decoding the collected metric. 

`level=debug msg="Error decoding JSON sent by druid: json: cannot unmarshal array into Go struct field DruidEmittedData.dataSource of type string"`

Regarding the error message, I suspect that maybe the exporter cannot parse metrics with some datasource values in some cases. 

For instance, there is no `druid_emitted_metrics` created for the metric collected from druid/middleManager with the datasource below:
`90df4ca9-7ae6-11e8-bf0a-0fb906e37fcf_events_user`

However I can see this datasource in `druid_datasource` metric.
`druid_datasource{datasource="90df4ca9-7ae6-11e8-bf0a-0fb906e37fcf_events_user"}`

On the other hand, the metric below is parsed and exposed as prometheus metric.

`{metrics 2020-06-17 11:53:57.146 +0000 UTC druid/middleManager 192.168.128.4:8117 0.18.0 ingest/sink/count 90df4ca9-7ae6-11e8-bf0a-0fb906e37fcf_events_user_activity 0}`

Prometheus metric is:
`druid_emitted_metrics{datasource="90df4ca9-7ae6-11e8-bf0a-0fb906e37fcf_events_user_activity",service="druid-middleManager", metric_name="ingest-sink-count"}`

**Comment by iamabhishek-dubey** [comment]
I guess this is a simple parsing issue, I will take a look at this
