### ISSUE TITLE
Concerning the next release

### ISSUE THREAD

**Issue by machine424** [opstree/druid-exporter#40]
Hello,

I congratulate you for the work that you are doing, we were wondering if it would be possible to release any time soon, we're interested in this fix: https://github.com/opstree/druid-exporter/pull/37

Thanks,
Keep up.

**Comment by iamabhishek-dubey** [comment]
Sure, we will be releasing this tomorrow :)

**Comment by Chester-Ong** [comment]
@machine424 you might want to wait for the next release instead, we are currently on standardising the parameters see: #43.

**Comment by machine424** [comment]
@Chester-Ong If this will take more than a couple of days, we would like to have a release now and leave your changes for the next release assuming that we can introduce breaking changes in new minor releases for now.

**Comment by iamabhishek-dubey** [comment]
I can create a pre-release for you but we will be working on standardizing the parameter and once it is done we will release it. Does this sound good to you?

**Comment by machine424** [comment]
Yes, this suits us. Thanks.

**Comment by iamabhishek-dubey** [comment]
You can use this one:- https://github.com/opstree/druid-exporter/releases/tag/v0.8-pre-release

let me know if you have any issues.

**Comment by iamabhishek-dubey** [comment]
A new release is created
https://github.com/opstree/druid-exporter/releases/tag/v0.8

**Comment by machine424** [comment]
Thanks, I will hassle a little more, the docker images were not build https://quay.io/repository/opstree/druid-exporter?tab=tags shouldn't this be triggered automatically?

**Comment by iamabhishek-dubey** [comment]
Yes, I agree with you. We will add the auto trigger for quay and docker hub

**Comment by iamabhishek-dubey** [comment]
![image](https://user-images.githubusercontent.com/26764731/87851183-f75f4900-c913-11ea-89f6-d25e0845e7b3.png)

**Comment by iamabhishek-dubey** [comment]
the automated trigger is added for new tags
