### ISSUE TITLE
Unsure about project objectives

### ISSUE THREAD

**Issue by Chester-Ong** [opstree/druid-exporter#43]
Great project thus far! However, I feel that there are some issues regarding the direction the exporter is taking. It seem like there there is a mismatch of objectives, i.e. a k8 environment and bare metal environment.

For example, in the emitted metrics, the host parameter has been changed to pod (k8 infra).
```go
// listener/druid-endpoint.go
gauge.With(prometheus.Labels{
    "metric_name": strings.Replace(metricName, "/", "-", 3),
    "service":     strings.Replace(serviceName, "/", "-", 3),
    "datasource":  datasource,
    "pod":         podName,
.Set(value)
```

I understand that podName is important in the k8 environment however, a more generic **host** should suffice, correct me if I'm wrong. I'll be submitting a few PR to restructure to do the reverse DNS lookup to obtain podname, whilst allowing host=localhost without errors.

@exherb kindly review the PR if it would solve your use case with k8.

**Comment by exherb** [comment]
renaming pod to host？

**Comment by Chester-Ong** [comment]
essentially that's about it, I've submitted a PR #44.

Another thing is to add the port back into host. This is dropped by your reverse DNS lookup but I added it back in. Do you mind just testing the PR on your end to see if it works with your k8 setup. I'm not that experienced in k8 so I can verify on that end.

**Comment by iamabhishek-dubey** [comment]
Sure I will test it

**Comment by iamabhishek-dubey** [comment]
I think we can close this issue now

**Comment by iamabhishek-dubey** [comment]
The new release is created 
https://github.com/opstree/druid-exporter/releases/tag/v0.8
