### ISSUE TITLE
Create a new grafana dashboard with better and useful insights

### ISSUE THREAD

**Issue by iamabhishek-dubey** [opstree/druid-exporter#47]

**Comment by iamabhishek-dubey** [comment]
@Chester-Ong and @exherb would one of you like to help on this one?

**Comment by Chester-Ong** [comment]
Hmm I was exploring with grafana for druid previously and this is very specific to the user's druid configuration. Depending on the monitors setup in **druid.monitoring.monitors**, there might be a large volume of metrics that would be missing if we were to go deep, on the other side, if we were to make it as generic as possible, it would not be sufficiently insightful.

My thoughts on this would be that this would just be a dashboard example for users to view as a guide, and for them to play around with grafana and configure their dashboard themselves.

**Comment by iamabhishek-dubey** [comment]
Good suggestion, I have created one basic dashboard and users can further customize it.
