### ISSUE TITLE
panic serving 127.0.0.1:47654: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by catalinmer** [opstree/druid-exporter#53]
Hi,
Shortly after start i get this errors (i have metrics collected but this panic message is logged continuously):

Aug 11 06:36:59 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:36:59Z" level=info msg="Druid exporter started listening on: 8080"
Aug 11 06:36:59 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:36:59Z" level=info msg="Metrics endpoint - http://0.0.0.0:8080/metrics"
Aug 11 06:36:59 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:36:59Z" level=info msg="Druid emitter endpoint - http://0.0.0.0:8080/druid"
Aug 11 06:36:59 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:36:59Z" level=info msg="Successfully collected data from druid emitter, druid/broker"
Aug 11 06:36:59 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:36:59Z" level=info msg="Successfully collected data from druid emitter, druid/broker"
Aug 11 06:36:59 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:36:59Z" level=info msg="Successfully collected data from druid emitter, druid/broker"
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:37:00Z" level=info msg="Successfully collected data from druid emitter, druid/middleManager"
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:37:00Z" level=info msg="Successfully collected data from druid emitter, druid/middleManager"
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:37:00Z" level=info msg="Successfully collected data from druid emitter, druid/middleManager"
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:37:00Z" level=info msg="Successfully collected data from druid emitter, druid/historical"
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: time="2020-08-11T06:37:00Z" level=info msg="Successfully collected data from druid emitter, druid/historical"
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: 2020/08/11 06:37:00 http: panic serving 127.0.0.1:47654: interface conversion: interface {} is nil, not string
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: goroutine 12 [running]:
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: net/http.(*conn).serve.func1(0xc0001da140)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:1767 +0x139
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: panic(0x8f6ba0, 0xc000274720)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: druid-exporter/listener.DruidHTTPEndpoint.func1(0xa415c0, 0xc0001342a0, 0xc0000ded00)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /go/src/druid-exporter/listener/druid_endpoint.go:33 +0x1578
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: net/http.HandlerFunc.ServeHTTP(0xc0000a7f60, 0xa415c0, 0xc0001342a0, 0xc0000ded00)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:2007 +0x44
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000122000, 0xa415c0, 0xc0001342a0, 0xc0000deb00)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: net/http.serverHandler.ServeHTTP(0xc000134000, 0xa415c0, 0xc0001342a0, 0xc0000deb00)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:2802 +0xa4
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: net/http.(*conn).serve(0xc0001da140, 0xa42c80, 0xc00028a280)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:1890 +0x875
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: created by net/http.(*Server).Serve
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:2927 +0x38e
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: 2020/08/11 06:37:00 http: panic serving 127.0.0.1:47656: interface conversion: interface {} is nil, not string
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: goroutine 13 [running]:
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: net/http.(*conn).serve.func1(0xc0001da1e0)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:1767 +0x139
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: panic(0x8f6ba0, 0xc0003711a0)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: druid-exporter/listener.DruidHTTPEndpoint.func1(0xa415c0, 0xc0001561c0, 0xc000158c00)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /go/src/druid-exporter/listener/druid_endpoint.go:33 +0x1578
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: net/http.HandlerFunc.ServeHTTP(0xc0000a7f60, 0xa415c0, 0xc0001561c0, 0xc000158c00)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:2007 +0x44
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000122000, 0xa415c0, 0xc0001561c0, 0xc000158a00)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: net/http.serverHandler.ServeHTTP(0xc000134000, 0xa415c0, 0xc0001561c0, 0xc000158a00)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:2802 +0xa4
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: net/http.(*conn).serve(0xc0001da1e0, 0xa42c80, 0xc0000690c0)
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:1890 +0x875
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: created by net/http.(*Server).Serve
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]:         /usr/local/go/src/net/http/server.go:2927 +0x38e
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: 2020/08/11 06:37:00 http: panic serving 127.0.0.1:47658: interface conversion: interface {} is nil, not string
Aug 11 06:37:00 ip-172-31-61-156 druid-exporter[6641]: goroutine 33 [running]:

**Comment by iamabhishek-dubey** [comment]
Thanks for this issue report, we will try to fix this ASAP.

**Comment by iamabhishek-dubey** [comment]
https://github.com/opstree/druid-exporter/releases/tag/v0.9-beta

You can use this binary

**Comment by iamabhishek-dubey** [comment]
quay.io/opstree/druid-exporter:v0.9-beta Docker image

**Comment by catalinmer** [comment]
I think it was from using -d "druid_url". if i replaced that with the env var `export DRUID_URL=http://druid.url` it works fine
