### ISSUE TITLE
druid_health_status returns 0 but druid services return true for health status

### ISSUE THREAD

**Issue by danghuagood** [opstree/druid-exporter#56]
when i use implementing commit: db1c4bd646675749fe6858e1cf82b26932b5d24b,
i got the stdout logs of druid exporter
![image](https://user-images.githubusercontent.com/8109501/90201464-8ecd9400-de0d-11ea-8714-d9def96bdc50.png)

the metric message:
![image](https://user-images.githubusercontent.com/8109501/90201565-ce947b80-de0d-11ea-9f7b-7f02e0d3b002.png)

the command:
/usr/local/bin/druid-exporter --druid.uri=http://10.18.64.247 --port=10086 --log.level=debug

**Comment by iamabhishek-dubey** [comment]
This `10.18.64.247` should be druid router and coordinator IP and port also need to be defined. For example:- http://<druid_router_ip>:8081. Make sure you define the IP and port of a valid druid.

**Comment by iamabhishek-dubey** [comment]
This is not a bug so closing this issue.
