### ISSUE TITLE
druid_health_status returns 0 value but druid services return true for health status

### ISSUE THREAD

**Issue by danghuagood** [opstree/druid-exporter#57]
after using implementing commit: db1c4bd646675749fe6858e1cf82b26932b5d24b, here is the messages
![image](https://user-images.githubusercontent.com/8109501/90353285-6e554200-e078-11ea-9ad8-97b8257f857f.png)

![image](https://user-images.githubusercontent.com/8109501/90353406-b1afb080-e078-11ea-8136-2f4697025f61.png)

the command:
/usr/local/bin/druid-exporter --druid.uri=http://10.18.64.247 --port=10086 --log.level=debug

**Comment by iamabhishek-dubey** [comment]
Have you read this comment I made on your previous issue
https://github.com/opstree/druid-exporter/issues/56

**Comment by iamabhishek-dubey** [comment]
This is not a bug you are providing the incomplete url of druid. You have to define the url and port of druid router service. Please check the above issue comment for more details
