### ISSUE TITLE
Can export metrics to prometheus

### ISSUE THREAD

**Issue by MateusHenriqueOliveira** [opstree/druid-exporter#58]
Hi folks, my team and I are try to send metrics to prometheus, we see that exporter is collecting data whoever we dont see this in prometheus, there is some config we have to do?
Using prometheus operator
Azure Kubernetes Services

**Comment by iamabhishek-dubey** [comment]
I guess you have to create a service monitor for druid exporter in Prometheus

**Comment by iamabhishek-dubey** [comment]
https://github.com/opstree/druid-exporter/blob/master/helm/templates/servicemonitor.yaml

**Comment by MateusHenriqueOliveira** [comment]
Yes, I create the serviceMonitor, but yet dont work, seems like something is missing, @iamabhishek-dubey do you know if I need to make some config like some clusterrolebinding or clusterrole for this exporter or for druid?

**Comment by iamabhishek-dubey** [comment]
No need for RBAC in druid exporter. This issue seems to be at the Prometheus level, have you compared the labels of service monitor with other service monitors. Also, have you checked in Prometheus service discovery that it is listing or not
