### ISSUE TITLE
Export bucketed latency metrics

### ISSUE THREAD

**Issue by ggarcia-te** [opstree/druid-exporter#62]
# Problem
When tracking query latencies it is very useful to compute percentiles to understand how the majority of queries are performing and any outliers.

Currently, this is not possible because the value emitted by druid is directly exported in the endpoint scraped by prometheus:
```
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical"} 9
```

# Proposal
It would be more useful to export buckets of metrics for the observed latencies:
```
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="1"} 5
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="5"} 5
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="10"} 5
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="20"} 6
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="50"} 6
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="100"} 7
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="250"} 10
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="500"} 10
druid_emitted_metrics{datasource="foo", metric_name="query-time", service="druid-historical", le="1000"} 10
```

In this case, all queries that have a latency of < 1 ms would increment the le="1" bucket counter. All queries that took < 5ms would increment the counter value of le="5" and le="1".

With this way of exporting latency metrics, it would be possible to compute dynamic percentiles via prometheus with the recommended approach (https://prometheus.io/docs/practices/histograms/#quantiles):
```
histogram_quantile(0.95, sum(rate(druid_emitted_metrics[5m])) by (le))
```

**Comment by iamabhishek-dubey** [comment]
@ggarcia-te this is a good proposal, I think we can start working on this

**Comment by iamabhishek-dubey** [comment]
We have added this feature with a different metric name. See https://github.com/opstree/druid-exporter/pull/64

**Comment by ggarcia-te** [comment]
Thanks @iamabhishek-dubey! That was amazingly quick
