### ISSUE TITLE
Panic when there is no available worker

### ISSUE THREAD

**Issue by desaintmartin** [opstree/druid-exporter#63]
If Druid cluster is in a state where there is no workers, druid-exporter will crash due to 
`hostname = workers[rand.Intn(len(workers))].hostname()`

where `rand.Intn` takes an strictly positive argument, but `workers` is `[]`

Should druid-exporter ignore those worker-related metrics where there is none?

**Comment by iamabhishek-dubey** [comment]
@desaintmartin I will check this error once and will add a condition to skip if `worker is []`

**Comment by iamabhishek-dubey** [comment]
This should be fixed in https://github.com/opstree/druid-exporter/pull/64
