### ISSUE TITLE
Add datasource row count

### ISSUE THREAD

**Issue by pedrohff** [opstree/druid-exporter#73]
Hi!
Me and my team use Druid ingesting data with kafka indexer, and I'd like to track any possible lag on Druid's side.
I've seen on Druid's UI that it displays the "Total rows" on the Datasources pane, and I'd like to bring this counter to the project, would it be usefull to it's users? If yes, I'd like to contribute.

With this data I could use Grafana to measure any kind of bottleneck in the process of gathering data from my origin datasource, passing through Kafka (with connect, monitored by kafka lag exporter) and getting processed on Druid.

**Comment by iamabhishek-dubey** [comment]
Yes, I think you can make this contribution :+1:

**Comment by iamabhishek-dubey** [comment]
PR is merged, closing this issue
