### ISSUE TITLE
Provide more metrics

### ISSUE THREAD

**Issue by schmichri** [opstree/druid-exporter#74]
FEATURE REQUEST
---
Hey there, 

additional Tasks Metrics would be useful to support HPA. 
```
* druid_tasks_pending
* druid_tasks_running
* druid_tasks_waiting
* druid_tasks_completed
```

Any change that you would implement them? 

Best

schmichri

**Comment by iamabhishek-dubey** [comment]
You can list the status of the task by using PromQL, like:-
```sql
count(druid_tasks_duration{task_status=!""}) by (task_status)
```

**Comment by schmichri** [comment]
Means I have to add custom rules on prometheus-adapter for a metrics which should be standard. I propose you reconsider this.

**Comment by iamabhishek-dubey** [comment]
Okay we will be reconsidering it

**Comment by iamabhishek-dubey** [comment]
Please use this release https://github.com/opstree/druid-exporter/releases/tag/v0.9. metrics are added

```sql
druid_running_tasks
druid_waiting_tasks
druid_completed_tasks
druid_pending_tasks
```

**Comment by schmichri** [comment]
Looks working. Thanks a lot!

**Comment by Aka-shi** [comment]
@schmichri Can you share on how you plan to deploy HPA with only task metrics?

**Comment by schmichri** [comment]
@Aka-shi :  I plan so scale a middlemanager (statefulset) when  there are too many pending tasks. The metrics are thanks to @iamabhishek-dubey are available now.

**Comment by Aka-shi** [comment]
Hey, @schmichri I understand the scale up. What I am more concerned is the scale down, if you are deploying HPA and when the controller scales up the middle manager pods based on pending tasks, the pending tasks count itself would become zero(ideally) which would in some time trigger a scale down. 

IMO, to properly scale up or down, we would also need the total worker capacity of the druid cluster and after that we can use this ratio `sum(druid_pending_tasks + druid_running_tasks)/druid_worker_capacity_total`. This would give a fair ratio to scale up/down. Thoughts?

**Comment by schmichri** [comment]
You are right. Didn't thought this through.
