### ISSUE TITLE
allow metric exclusions

### ISSUE THREAD

**Issue by bbecker-te** [opstree/druid-exporter#77]
The metric-exporter is producing thousands of metrics. Too many metrics can overload Prometheus. We only need some of the metrics. It would be nice if there could be an option to supply a regexp to exclude metrics that matched it (or alternatively include them).

**Comment by iamabhishek-dubey** [comment]
You can actually do that at Prometheus level.
https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus

**Comment by bbecker-te** [comment]
Thanks, I will look into it.

**Comment by bbecker-te** [comment]
The metrics emitted by the druid-exporter are all generically grouped into a single `druid_emitted_metrics" metric`. Individual metrics are specified with the `metric_name` label. Here are some sample lines from the prometheus scrape target to illustrate:
```
druid_emitted_metrics{datasource="http_1m_rollup",host="10.202.7.177:8100",metric_name="jetty-numOpenConnections",pod="10-202-7-177",service="druid-middleManager-tier2"} 0
druid_emitted_metrics{datasource="http_1m_rollup",host="10.202.7.177:8100",metric_name="jvm-bufferpool-capacity",pod="10-202-7-177",service="druid-middleManager-tier2"} 5.25921679e+08
druid_emitted_metrics{datasource="http_1m_rollup",host="10.202.7.177:8100",metric_name="jvm-bufferpool-count",pod="10-202-7-177",service="druid-middleManager-tier2"} 7
```
While the suggestion of using `metric_relabel_configs` works to drop or keep metrics by name, it does not seem like it would work in this case, because we want to restrict by label, not by metric name (everything is part of the `druid_emitted_metrics` metric). Hopefully I am misunderstanding and there really is an easy way to do it.
