### ISSUE TITLE
Error on v0.9: Unable to read JSON response: Unexpected EOF

### ISSUE THREAD

**Issue by tanisdlj** [opstree/druid-exporter#81]
After the latest release (just downloaded and build) I can see this line happening quite often:
`Jan 14 11:01:41 druid-exporter-1 druid-prometheus-exporter[2114]: time="2021-01-14T11:01:41Z" level=error msg="Unable to read JSON response: unexpected EOF"`

**Comment by iamabhishek-dubey** [comment]
This is not an actual error, the druid is emitting data to the druid exporter. If the payload is not JSON, this message will come. You can ignore this because it is not breaking anything.

**Comment by tanisdlj** [comment]
Thanks a lot!
