### ISSUE TITLE
Total worker capacity as a metric

### ISSUE THREAD

**Issue by Aka-shi** [opstree/druid-exporter#82]
As discussed in #74, pending/running task alone wouldn't help in scaling up/down using HPA. We would also need the total worker capacity of the druid cluster to decide if the HPA controller can scale down. An additional metric like `druid_worker_capacity_total` would be useful. 

As the exporter already emits the workers used metric, this would be a pretty small change. I tried to push my branch to contribute but I get access denied. @iamabhishek-dubey can you help me out here?

**Comment by iamabhishek-dubey** [comment]
You can simply fork the repo and raise the Pull Request :smile:

**Comment by Aka-shi** [comment]
@iamabhishek-dubey raised a PR. Please help in reviewing and merging it. Thank You!

**Comment by iamabhishek-dubey** [comment]
#84 is merged
