### ISSUE TITLE
no keys for druid auth in values.yaml for helm chart

### ISSUE THREAD

**Issue by UsamaMehboob** [opstree/druid-exporter#85]
Hi, I was trying to deploy using helm chart and I dont see any option for username and password to authenticate with the druid. I get this message.

level=error msg="Possible issue can be with Druid's URL, Username or Password"

**Comment by UsamaMehboob** [comment]
I can make a PR, if you approve?

**Comment by iamabhishek-dubey** [comment]
Sure, we welcome feedback and contributions

**Comment by UsamaMehboob** [comment]
thanks @iamabhishek-dubey ; One query is does this exporter support scraping druid monitors ?
```
org.apache.druid.java.util.metrics.SysMonitor
org.apache.druid.server.metrics.HistoricalMetricsMonitor
org.apache.druid.java.util.metrics.JvmMonitor
org.apache.druid.java.util.metrics.JvmCpuMonitor
org.apache.druid.java.util.metrics.JvmThreadsMonitor
org.apache.druid.segment.realtime.RealtimeMetricsMonitor
org.apache.druid.server.metrics.QueryCountStatsMonitor
org.apache.druid.server.metrics.TaskCountStatsMonitor
```

**Comment by iamabhishek-dubey** [comment]
> thanks @iamabhishek-dubey ; One query is does this exporter support scraping druid monitors ?
> https://druid.apache.org/docs/latest/configuration/index.html#enabling-metrics
> 
> ```
> org.apache.druid.java.util.metrics.SysMonitor
> org.apache.druid.server.metrics.HistoricalMetricsMonitor
> org.apache.druid.java.util.metrics.JvmMonitor
> org.apache.druid.java.util.metrics.JvmCpuMonitor
> org.apache.druid.java.util.metrics.JvmThreadsMonitor
> org.apache.druid.segment.realtime.RealtimeMetricsMonitor
> org.apache.druid.server.metrics.QueryCountStatsMonitor
> org.apache.druid.server.metrics.TaskCountStatsMonitor
> ```

Not right now but it would be a great feature

**Comment by iamabhishek-dubey** [comment]
Fixed in https://github.com/opstree/druid-exporter/pull/93
