### ISSUE TITLE
Druid Metric Dimensions as Labels

### ISSUE THREAD

**Issue by busecolak** [opstree/druid-exporter#9]
Hello, 

Druid emits some of the metrics with dimensions such as datasource, tier, taskid etc. It is possible to use these dimension values as Prometheus metric labels. 

It would be beneficial to see metrics by datasource. Is there any plan to add labels (mostly datasource) to exported metrics?

**Comment by iamabhishek-dubey** [comment]
Can you post a sample JSON example which you are talking about? We will try to incorporate those as well

**Comment by busecolak** [comment]
Here is an example metric emitted with dataSource value:

`{
   "feed":"metrics",
   "timestamp":"2020-04-14T07:07:34.096Z",
   "service":"druid/coordinator",
   "host":"localhost:8081",
   "version":"0.17.0",
   "metric":"segment/unavailable/count",
   "value":0,
   "dataSource":"wikipedia"
}`

**Comment by iamabhishek-dubey** [comment]
Hmm seems like a no big change. Thanks for the feedback we will try to the changes ASAP.

**Comment by iamabhishek-dubey** [comment]
This release has this enhancement

https://github.com/opstree/druid-exporter/releases/tag/v0.4

**Comment by busecolak** [comment]
Thanks for this quick enhancement! 

Could you please also push a new docker image?

**Comment by iamabhishek-dubey** [comment]
You can use this image
quay.io/opstree/druid-exporter:v0.4
