### ISSUE TITLE
the centos7 cannot execute

### ISSUE THREAD

**Issue by taoyantu** [opstree/druid-exporter#91]
hello,master,I download the druid-exporter <druid-exporter-v0.9-linux-amd64.gz>， my system is centos 7.2 ，
1. gzip -d druid-exporter-v0.9-linux-amd64.gz 
2.  chmod 755   druid-exporter-v0.9-linux-amd64
3. ./druid-exporter-v0.9-linux-amd64

the error is  cannot execute

please help me ,thank you

**Comment by iamabhishek-dubey** [comment]
Can you use `tar -xvzf` to extract binary

**Comment by iamabhishek-dubey** [comment]
Use

```shell
tar -xvzf druid-exporter-v0.9-linux-amd64.gz
```
