### ISSUE TITLE
how to config to get more monitor ？

### ISSUE THREAD

**Issue by taoyantu** [opstree/druid-exporter#95]
hello master :
 i use the  druid-exporter in my druid cluster ，i run it  ./druid-exporter --durid.uri=http://172.16.1.84:8888 ，this is  router node ，i visit http://172.16.1.84:8080/metrics ,  can see the monitoring items, but very few, only some druid task monitoring (druid_completed_tasks, druid_peding_tasks .......), druid segment monitoring (druid_segment_count, deruid_segment_size ......), druid_healthe ,druid_datasource, there are too few monitoring items. How to configure this to enable more monitoring? 
i config the apache-druid-0.20.0/conf/druid/cluster/_common/common.runtime.properties ，

druid.emitter=http
druid.emitter.http.recipientBaseUrl=http://172.16.1.84:8080/druid

But when I visited http://172.16.1.84:8080/druid, it was blank, and I couldn’t see any monitoring content.

please help me ,how to config can show more and more monitor？
thank You!

**Comment by iercan** [comment]
I have same issue. After some point I stopped to get druid_emitted_metrics on grafana. Then I checked `http://exporter-domain/metrics` and realized these metrics not there. Then I downgraded to version 0.8 and they came back again. Looks like there is something wrong with new version.

**Comment by iamabhishek-dubey** [comment]
Yes I guess something is messed up, I will try to fix this issue ASAP

**Comment by iamabhishek-dubey** [comment]
This issue persists because the image was not updated, I have updated the image on [quay.io](quay.io)
